version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - "./local.env"
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  
  app:
    build: "../rooms"
    restart: always
    ports:
      - "80:8000"
    env_file:
      - "./local.env"
    depends_on:
      - db
