version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - "./local.env"
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  
#  redis: 
#    image: redis
#    restart: always
#   ports:
#      - "6379:6379"
#    volumes:    
#      - "./redisdata:/data"

#  app:
#    build: "../plaid_django"
#    restart: always
#    ports:
#      - "80:8000"
#    env_file:
#      - "./local.env"
#    depends_on:
#      - db
#      - redis

