# Generated by Django 2.2.2 on 2019-06-18 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_auto_20190618_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='landmarks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=3),
        ),
    ]
